(()=>{
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),targets=['S','Y','N','Q'],speeds=[220,190,165,140],$=id=>document.getElementById(id),views=[...document.querySelectorAll('.view')];
const state={stage:0,index:0,reel:null,reelStart:0,reelPos:0,locked:false,letterTries:0,continues:0,running:false,start:0,frame:null,runFrame:null,runStart:0,level1Elapsed:0,mode:'visible',last:null,lastRun:null,returnView:'homeView',afterAd:null,boardMode:'speed'};
const dateKey=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Copenhagen',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),displayDate=new Intl.DateTimeFormat('da-DK',{timeZone:'Europe/Copenhagen',weekday:'long',day:'numeric',month:'long'}).format(new Date()),hash=[...dateKey].reduce((n,c)=>((n<<5)-n+c.charCodeAt(0))|0,0),target=5+(Math.abs(hash*9301+49297)%500)/100;
const fmt=n=>Number(n).toFixed(2).replace('.',','),fmtRun=n=>{const m=Math.floor(n/60),s=n-m*60;return `${String(m).padStart(2,'0')}:${s.toFixed(2).padStart(5,'0').replace('.',',')}`},buzz=p=>navigator.vibrate?.(p),runElapsed=()=>(performance.now()-state.runStart)/1000;
function show(id){views.forEach(v=>v.classList.toggle('active',v.id===id));const action=['boardView','gameView','masterView'].includes(id);$('backBtn').classList.toggle('hidden',!action);$('backBtn').textContent=id==='boardView'?'← Tilbage':'↻ Forfra';$('backBtn').dataset.action=id==='boardView'?'back':'restart';$('homeBtn').classList.toggle('hidden',id==='homeView');$('boardBtn').classList.toggle('hidden',['boardView','gameView','masterView'].includes(id));if(id==='boardView')renderBoard()}
function update(){const unlocked=localStorage.getItem('synq-blind-unlocked')===dateKey;$('dailyText').textContent=displayDate[0].toUpperCase()+displayDate.slice(1);$('targetTitle').textContent=`Stop på ${fmt(target)}`;$('boardTarget').textContent=`Dagens mål · ${fmt(target)} sek.`;$('blindBtn').disabled=!unlocked;$('blindBtn').textContent=unlocked?'Level 3 · Blind Master':'Level 3 låses op efter Level 2'}
function progress(){$('progress').innerHTML=targets.map((l,i)=>`<span class="prog ${i<state.stage?'done':i===state.stage?'target':''}">${l}</span>`).join('');$('stageLabel').textContent=`Level 1 · Bogstav ${state.stage+1} af 4`;$('stageTitle').textContent=`Ram ${targets[state.stage]}`;$('tries').textContent=`Forsøg ${state.letterTries+1} af 2 · ${2-state.continues} continues tilbage`}
function startRunClock(){cancelAnimationFrame(state.runFrame);const tick=()=>{const v=`Samlet tid · ${fmtRun(runElapsed())}`;$('runClock').textContent=v;$('masterRunClock').textContent=v;state.runFrame=requestAnimationFrame(tick)};tick()}
$('reelTrack').innerHTML=Array.from({length:78},(_,i)=>`<span class="reel-item">${alphabet[i%26]}</span>`).join('');const reelItems=[...document.querySelectorAll('.reel-item')];
function drawReel(pos){const h=reelItems[0].offsetHeight,current=Math.round(pos);$('reelTrack').style.transform=`translate3d(0,${-((pos+.5)*h)}px,0)`;reelItems.forEach((el,i)=>{const d=Math.abs(i-current);el.classList.toggle('current',d===0);el.classList.toggle('near',d===1)})}
function beginGame(){cancelAnimationFrame(state.reel);cancelAnimationFrame(state.runFrame);state.stage=0;state.letterTries=0;state.continues=0;state.index=Math.floor(Math.random()*26);state.locked=false;state.runStart=performance.now();state.level1Elapsed=0;state.mode='letters';show('gameView');progress();startRunClock();spin()}
function spin(){cancelAnimationFrame(state.reel);state.locked=false;state.reelPos=26+state.index;state.reelStart=performance.now();const animate=now=>{state.reelPos=26+state.index+(now-state.reelStart)/speeds[state.stage];if(state.reelPos>=52){state.index=Math.round(state.reelPos)%26;state.reelStart=now;state.reelPos=26+state.index}drawReel(state.reelPos);state.reel=requestAnimationFrame(animate)};state.reel=requestAnimationFrame(animate)}
function advanceLetter(){state.letterTries=0;state.stage++;if(state.stage===4){state.level1Elapsed=runElapsed();setTimeout(()=>beginMaster('visible'),350)}else{progress();setTimeout(spin,350)}}
function showLetterFail(hit,goal){state.letterTries++;const first=state.letterTries<2,canContinue=state.continues<2;$('failMark').textContent=hit;$('failTitle').textContent=first?'Næsten':canContinue?'To forsøg brugt':'Øv, du klarede den ikke';$('failCopy').textContent=first?`Du ramte ${hit}. Du har ét forsøg mere på ${goal}.`:canContinue?`Du ramte ${hit}. Brug en af dine ${2-state.continues} continues for at få ${goal}, eller start forfra.`:'Begge annonce-continues er brugt. Dit speedrun er slut, og du skal starte helt forfra.';$('retryBtn').style.display=first?'block':'none';$('retryBtn').textContent='Prøv bogstavet igen';$('continueAdBtn').style.display=!first&&canContinue?'block':'none';$('restartBtn').style.display=!first?'inline-block':'none';$('restartBtn').textContent='Start hele løbet forfra';$('failure').classList.add('open')}
function stop(){if(state.locked)return;state.locked=true;cancelAnimationFrame(state.reel);const snapped=Math.round(state.reelPos);state.index=snapped%26;drawReel(snapped);const hit=alphabet[state.index],goal=targets[state.stage];if(hit===goal){buzz(24);advanceLetter()}else{buzz([45,45,80]);showLetterFail(hit,goal)}}
function beginMaster(mode){cancelAnimationFrame(state.reel);state.mode=mode;state.running=false;cancelAnimationFrame(state.frame);$('timerValue').textContent='0,00';$('timer').className='timer';$('timerHint').textContent='Tryk for at starte';$('masterLabel').textContent=mode==='visible'?'Level 2 · Visible Master':'Level 3 · Blind Master';$('masterCopy').textContent=mode==='visible'?'Tiden er synlig · ram inden for ±0,10':'Tiden forsvinder efter ét sekund';$('masterRunClock').style.display=mode==='visible'?'block':'none';show('masterView')}
function tapTimer(){if(!state.running){state.running=true;state.start=performance.now();$('timerHint').textContent='Tryk for at stoppe';const tick=()=>{const t=(performance.now()-state.start)/1000;$('timerValue').textContent=fmt(t);if(state.mode==='blind'&&t>=1.05)$('timer').classList.add('hidden-time');state.frame=requestAnimationFrame(tick)};tick()}else{const t=(performance.now()-state.start)/1000;state.running=false;cancelAnimationFrame(state.frame);buzz(35);state.last={time:t,delta:Math.abs(t-target),signed:t-target};state.mode==='visible'?finishVisible():result()}}
function finishVisible(){if(state.last.delta<=.1){const total=runElapsed();cancelAnimationFrame(state.runFrame);state.lastRun={total,level1:state.level1Elapsed,level2:total-state.level1Elapsed};localStorage.setItem('synq-blind-unlocked',dateKey);$('totalTime').textContent=fmtRun(total);$('level1Time').textContent=fmtRun(state.lastRun.level1);$('level2Time').textContent=fmtRun(state.lastRun.level2);$('runUsername').value=localStorage.getItem('synq-name')||'';$('runMessage').textContent='';update();show('runResultView')}else{$('failMark').textContent=`±${fmt(state.last.delta)}`;$('failTitle').textContent='Ikke tæt nok';$('failCopy').textContent='Du skal lande inden for ±0,10 sekunder. Den samlede tid fortsætter.';$('retryBtn').style.display='block';$('retryBtn').textContent='Prøv Level 2 igen';$('continueAdBtn').style.display='none';$('restartBtn').style.display='inline-block';$('failure').classList.add('open')}}
function result(){const s=state.last,sign=s.signed>=0?'+':'−';$('delta').textContent=`${sign}${fmt(Math.abs(s.signed))}`;$('resTarget').textContent=fmt(target);$('resTime').textContent=fmt(s.time);$('status').textContent=s.delta<.01?'Perfekt timing. Du er i SYNQ.':`Kun ${fmt(s.delta)} sekunder fra perfekt`;$('badge').textContent=s.delta<.05?'Master timing':'SYNQ gennemført';$('message').textContent='';$('username').value=localStorage.getItem('synq-name')||'';show('resultView')}
function showAd(next,chosen=false){state.afterAd=next;document.querySelector('.ad-label').textContent=chosen?'Annonce · continue':'Annonce';$('ad').classList.add('open');$('adClose').style.display='none';let n=15+Math.floor(Math.random()*6);$('adCount').textContent=`Fortsætter om ${n}`;const timer=setInterval(()=>{n--;$('adCount').textContent=n?`Fortsætter om ${n}`:'Klar';if(!n){clearInterval(timer);$('adClose').style.display='block'}},1000)}function closeAd(){$('ad').classList.remove('open');const next=state.afterAd;state.afterAd=null;next?.()}
function naturalGap(){return Number(localStorage.getItem('synq-natural-gap')||3)}function resetNatural(){localStorage.setItem('synq-natural-count','0');localStorage.setItem('synq-natural-gap',String(2+Math.floor(Math.random()*3)))}function naturalGate(next){const count=Number(localStorage.getItem('synq-natural-count')||0)+1;if(count>=naturalGap()){resetNatural();showAd(next,false)}else{localStorage.setItem('synq-natural-count',String(count));next()}}function startFresh(){cancelAnimationFrame(state.reel);cancelAnimationFrame(state.runFrame);state.running=false;cancelAnimationFrame(state.frame);naturalGate(beginGame)}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function cleanName(input,message){const name=input.value.trim().replace(/[<>]/g,'').slice(0,18);if(name.length<2){message.style.color='var(--red)';message.textContent='Skriv mindst 2 tegn';return null}localStorage.setItem('synq-name',name);return name}
function storeBest(key,name,item,metric){const board=JSON.parse(localStorage.getItem(key)||'[]'),old=board.find(x=>x.name.toLowerCase()===name.toLowerCase());if(!old||item[metric]<old[metric]){if(old)board.splice(board.indexOf(old),1);board.push({name,...item})}board.sort((a,b)=>a[metric]-b[metric]);localStorage.setItem(key,JSON.stringify(board.slice(0,100)));return !old||item[metric]<old[metric]}
function save(){if(!state.last)return;const name=cleanName($('username'),$('message'));if(!name)return;const ok=storeBest(`synq-blind-${dateKey}`,name,{time:state.last.time,delta:state.last.delta},'delta');$('message').style.color='var(--green)';$('message').textContent=ok?'Din bedste præcision er gemt':'Din bedste score er allerede bedre'}function saveRun(){if(!state.lastRun)return;const name=cleanName($('runUsername'),$('runMessage'));if(!name)return;const ok=storeBest(`synq-speed-${dateKey}`,name,state.lastRun,'total');$('runMessage').style.color='var(--green)';$('runMessage').textContent=ok?'Din speedrun er gemt':'Din bedste tid er allerede hurtigere'}
function renderBoard(){document.querySelectorAll('.board-tab').forEach(b=>b.classList.toggle('active',b.dataset.board===state.boardMode));const speed=state.boardMode==='speed',b=JSON.parse(localStorage.getItem(`${speed?'synq-speed':'synq-blind'}-${dateKey}`)||'[]');$('board').innerHTML=b.length?b.map((x,i)=>`<div class="board-row"><div class="rank">${String(i+1).padStart(2,'0')}</div><div class="player">${esc(x.name)}</div><div class="score"><b>${speed?fmtRun(x.total):`±${fmt(x.delta)}`}</b><span>${speed?'Level 1–2':`${fmt(x.time)} sek.`}</span></div></div>`).join(''):`<div class="empty">Ingen resultater endnu.<br>Bliv den første på ${speed?'Fastest Run':'Closest Time'}.</div>`}function board(from){state.returnView=from;show('boardView')}
$('startBtn').onclick=startFresh;$('blindBtn').onclick=()=>{if(!$('blindBtn').disabled)naturalGate(()=>beginMaster('blind'))};$('reel').onclick=stop;$('timer').onclick=tapTimer;$('retryBtn').onclick=()=>{$('failure').classList.remove('open');state.mode==='visible'?beginMaster('visible'):spin()};$('continueAdBtn').onclick=()=>{$('failure').classList.remove('open');state.continues++;showAd(advanceLetter,true)};$('restartBtn').onclick=()=>{$('failure').classList.remove('open');startFresh()};$('saveBtn').onclick=save;$('username').onkeydown=e=>{if(e.key==='Enter')save()};$('saveRunBtn').onclick=saveRun;$('runUsername').onkeydown=e=>{if(e.key==='Enter')saveRun()};$('goBlindBtn').onclick=()=>naturalGate(()=>beginMaster('blind'));$('runAgainBtn').onclick=startFresh;$('againBtn').onclick=()=>naturalGate(()=>beginMaster('blind'));$('resultHome').onclick=()=>show('homeView');$('homeBtn').onclick=()=>{cancelAnimationFrame(state.reel);cancelAnimationFrame(state.runFrame);cancelAnimationFrame(state.frame);state.running=false;$('failure').classList.remove('open');show('homeView')};$('boardBtn').onclick=()=>board('homeView');$('resultBoard').onclick=()=>board('resultView');$('backBtn').onclick=()=>$('backBtn').dataset.action==='restart'?startFresh():show(state.returnView);document.querySelectorAll('.board-tab').forEach(b=>b.onclick=()=>{state.boardMode=b.dataset.board;renderBoard()});$('adClose').onclick=closeAd;
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running){state.running=false;cancelAnimationFrame(state.frame);$('timerValue').textContent='0,00';$('timer').className='timer';$('timerHint').textContent='Tryk for at starte'}});if(!localStorage.getItem('synq-natural-gap'))resetNatural();update();progress();
})();
