window.latestStories=[
  {c:"Danmark",t:"Otte anholdt efter groft overfald",d:"Midt- og Vestsjællands Politi har anholdt otte personer i en sag om grov vold.",time:"21:35",src:"Midt- og Vestsjællands Politi",url:"https://politi.dk/nyhedsliste?district=Midt-og-Vestsjaellands-Politi",body:["Otte personer er blevet anholdt i forbindelse med et groft overfald, oplyser Midt- og Vestsjællands Politi.","Efterforskningen fortsætter, og politiets officielle nyhedsliste bliver opdateret, når der kan gives flere oplysninger om sagen."]},
  {c:"Danmark",t:"54-årig idømt to års fængsel for partnervold",d:"En mand er dømt i en alvorlig sag om gentagen vold mod sin partner.",time:"20:48",src:"Politiet",url:"https://politi.dk/",body:["En 54-årig mand er blevet idømt to års fængsel i en sag om partnervold. Ifølge politiets omtale omfattede sagen blandt andet brug af en ukrudtsbrænder.","Dommen er en del af dagens nationale politiopdateringer. Den originale meddelelse hos politiet indeholder sagens dokumenterede oplysninger."]},
  {c:"Danmark",t:"44-årig får otte års fængsel efter dødelig vold i Esbjerg",d:"Retten har afsagt dom i en alvorlig voldssag, hvor et menneske mistede livet.",time:"19:57",src:"Syd- og Sønderjyllands Politi",url:"https://politi.dk/",body:["En 44-årig er idømt otte års fængsel for vold med døden til følge i Esbjerg, fremgår det af politiets seneste nyheder.","Dommen afslutter retssagen, mens yderligere detaljer og eventuelle oplysninger om anke skal hentes hos myndighederne."]},
  {c:"Danmark",t:"Politiet søger pige efter Køge Festuge",d:"En savnet pige indgår i dagens døgnrapport fra Midt- og Vestsjællands Politi.",time:"18:46",src:"Midt- og Vestsjællands Politi",url:"https://politi.dk/midt-og-vestsjaellands-politi/doegnrapporter/midt-og-vestsjaellands-politi-uddrag-af-doegnrapporten-den-01-september-2026/2026/09/01",body:["Midt- og Vestsjællands Politi omtaler eftersøgningen af en savnet pige i forbindelse med Køge Festuge i døgnrapporten for 1. september.","Borgere bør følge politiets officielle kanaler for signalement, kontaktoplysninger og den seneste status frem for at dele ubekræftede oplysninger."]},
  {c:"Danmark",t:"Kvinde fængslet efter trusler",d:"En sag om trusler har ført til varetægtsfængsling, fremgår det af dagens døgnrapport.",time:"17:52",src:"Midt- og Vestsjællands Politi",url:"https://politi.dk/midt-og-vestsjaellands-politi/doegnrapporter/midt-og-vestsjaellands-politi-uddrag-af-doegnrapporten-den-01-september-2026/2026/09/01",body:["En kvinde er blevet fængslet efter en sag om trusler, oplyser Midt- og Vestsjællands Politi i dagens uddrag af døgnrapporten.","Rapporten samler desuden flere hændelser fra politikredsen, herunder sager om påvirkede trafikanter."]},
  {c:"Danmark",t:"Hævede brønddæksler og gaspistol blandt døgnets hændelser",d:"Nordsjællands Politi samler nattens og morgenens markante sager i en ny døgnrapport.",time:"16:41",src:"Nordsjællands Politi",url:"https://politi.dk/",body:["Hævede brønddæksler, en gaspistol og flere færdselsforhold er blandt de hændelser, Nordsjællands Politi omtaler i den seneste døgnrapport.","Døgnrapporten er et foreløbigt overblik. Oplysningerne kan ændre sig, efterhånden som politiets undersøgelser skrider frem."]},
  {c:"Danmark",t:"Politiet advarer efter tricktyveri og bedrageriforsøg",d:"Flere hændelser i Nordsjælland får politiet til igen at rette fokus mod svindel.",time:"15:33",src:"Nordsjællands Politi",url:"https://politi.dk/",body:["Tricktyveri og et forsøg på bedrageri indgår i Nordsjællands Politis seneste døgnrapport.","Politiet anbefaler generelt, at man er kritisk over for uventede henvendelser og aldrig udleverer kort, koder eller personlige oplysninger til fremmede."]},
  {c:"Danmark",t:"Omkring 35 traktorer på vej mod demonstration i Aarhus",d:"Trafikken kan blive påvirket, når traktorer kører mod Universitetsparken.",time:"14:29",src:"Østjyllands Politi",url:"https://politi.dk/politi-update/meddelelse?uri=15128798",body:["Omkring 35 traktorer er på vej mod Universitetsparken i Aarhus i forbindelse med en demonstration, oplyser politiet.","Trafikanter i området bør følge de aktuelle trafikmeldinger og være forberedt på langsommere trafik omkring ruten."]},
  {c:"Danmark",t:"Aabenraa indgår budgetaftale for 2027",d:"Et enigt byråd vil prioritere den daglige drift og fortsatte investeringer i velfærd.",time:"13:18",src:"Aabenraa Kommune / Via Ritzau",url:"https://via.ritzau.dk/pressemeddelelse/15128628/budget-2027-fokus-pa-driften?lang=da&publisherId=11824589",body:["Aabenraa Byråd har indgået en enstemmig aftale om kommunens budget for 2027.","Aftalen lægger ifølge kommunen vægt på stabil drift og fortsatte investeringer i velfærdsområderne. De konkrete bevillinger fremgår af kommunens budgetmateriale."]},
  {c:"Danmark",t:"Viborg Kommune henter ny chef i Transportministeriet",d:"En ny leder skal styrke kommunens arbejde med mobilitet og infrastruktur.",time:"12:07",src:"Viborg Kommune / Via Ritzau",url:"https://via.ritzau.dk/pressemeddelelse/15129772/viborg-kommune-henter-ny-chef-i-transportministeriet?lang=da&publisherId=13561792",body:["Viborg Kommune har ansat en ny chef med erfaring fra Transportministeriet.","Ansættelsen skal tilføre statslig erfaring til kommunens arbejde med transport, mobilitet og de kommende infrastrukturbeslutninger."]},

  {c:"Verden",t:"Massivt russisk angreb rammer Kyiv i 12 timer",d:"Mindst 12 er dræbt efter en omfattende bølge af droner og missiler mod Ukraine.",time:"21:12",src:"Associated Press",url:"https://apnews.com/article/7564a892bfb99a853aa150c8710b7985",body:["Kyiv og andre dele af Ukraine blev ramt af et omkring 12 timer langt russisk bombardement. Mindst 12 mennesker er ifølge myndighederne blevet dræbt.","Angrebet omfattede mere end 218 droner og missiler og fortsatte en række dages intensive angreb. Redningsarbejdet og opgørelsen af skader fortsætter."]},
  {c:"Verden",t:"To tankskibe med saudisk olie angrebet ved Hormuz",d:"Angrebene øger presset på en af verdens vigtigste ruter for energihandel.",time:"19:44",src:"Reuters",url:"https://www.reuters.com/business/energy/two-tankers-carrying-saudi-oil-attacked-strait-hormuz-2026-09-01/",body:["To tankskibe med saudisk olie er blevet angrebet ved Hormuzstrædet. Der er ikke meldt om tilskadekomne.","Hændelserne skærper bekymringen for forsyningssikkerheden, fordi en betydelig del af verdens søbårne olie passerer gennem det smalle farvand."]},
  {c:"Verden",t:"Fødevarehjælp til Vestbredden halveres",d:"Manglende finansiering tvinger FN's Fødevareprogram til at skære støtten markant.",time:"18:24",src:"Associated Press",url:"https://apnews.com/article/c85fd56b4ad92ec63146d8f6f9cf5a87",body:["FN's Fødevareprogram halverer sin hjælp på Vestbredden på grund af mangel på penge.","Antallet af mennesker, der modtager støtte, ventes at falde fra omkring 400.000 til 200.000. Organisationen advarer om, at flere familier dermed vil stå uden den hidtidige hjælp."]},
  {c:"Verden",t:"Putin hævder nye russiske fremstød i Donetsk",d:"Ruslands præsident siger, at styrker har vundet terræn, mens kampene fortsætter.",time:"16:58",src:"Reuters",url:"https://www.reuters.com/world/",body:["Vladimir Putin hævder, at russiske styrker har vundet omkring 270 kvadratkilometer i Donetsk og omringet ukrainske enheder.","Oplysninger fra krigszonen kan ikke altid verificeres uafhængigt med det samme. Ukraine og Rusland giver ofte forskellige beskrivelser af udviklingen ved fronten."]},
  {c:"Verden",t:"Mexicanske soldater dræber formodet kartelleder",d:"En militæroperation har ramt en person, som myndighederne forbinder med organiseret kriminalitet.",time:"15:37",src:"Reuters",url:"https://www.reuters.com/world/",body:["Mexicanske soldater har dræbt en formodet leder i et narkokartel under en operation, oplyser myndighederne.","Sagen kommer midt i et vedvarende pres på regeringen for at dæmpe kartelvold og styrke sikkerheden i de hårdest ramte områder."]},

  {c:"Politik",t:"Folketinget behandler krav om ID-kort på byggepladser",d:"Et nyt lovforslag skal gøre det lettere at kontrollere, hvem der arbejder på byggepladser.",time:"20:31",src:"Folketinget",url:"https://www.ft.dk/aktuelt/nyheder/2026/08/uge-36-i-folketinget",body:["Folketinget tager i uge 36 hul på et forslag om ID-kort på byggepladser.","Forslaget er blandt ti lovforslag på tirsdagens program og skal nu gennem den almindelige parlamentariske behandling med debat, udvalg og afstemninger."]},
  {c:"Politik",t:"Forslag vil sætte flere solceller på offentlige bygninger",d:"Folketinget skal drøfte nye rammer for solenergi på statens og kommunernes tage.",time:"18:53",src:"Folketinget",url:"https://www.ft.dk/aktuelt/nyheder/2026/08/uge-36-i-folketinget",body:["Solceller på offentlige bygninger er på Folketingets dagsorden i denne uge.","Debatten handler om, hvordan offentlige tage kan bidrage mere til energiproduktionen, og hvilke økonomiske og praktiske regler der skal gælde."]},
  {c:"Politik",t:"Ung alder skal ikke automatisk mildne straf for grov vold",d:"Et forslag i Folketinget vil ændre betydningen af gerningspersonens alder i alvorlige voldssager.",time:"17:26",src:"Folketinget",url:"https://www.ft.dk/aktuelt/nyheder/2026/08/uge-36-i-folketinget",body:["Folketinget førstebehandler et forslag om, at ung alder ikke i sig selv skal være en formildende omstændighed ved alvorlig vold.","Forslaget skal nu diskuteres politisk og behandles i udvalg, før Folketinget tager endelig stilling."]},
  {c:"Politik",t:"El-nettets kapacitet kommer til politisk debat",d:"Folketinget skal diskutere, hvordan begrænset netkapacitet skal prioriteres.",time:"15:49",src:"Folketinget",url:"https://www.ft.dk/aktuelt/nyheder/2026/08/uge-36-i-folketinget",body:["Kapaciteten i det danske elnet og prioriteringen mellem nye tilslutninger er blandt ugens politiske emner.","Spørgsmålet er blevet mere presserende i takt med elektrificering, datacentre og ny vedvarende energi, som alle stiller større krav til nettet."]},
  {c:"Politik",t:"Forslag: Ingen skal betale mere i skat, end de tjener",d:"Et nyt beslutningsforslag rejser debat om samspillet mellem skatter og indkomst.",time:"14:16",src:"Folketinget",url:"https://www.ft.dk/aktuelt/nyheder/2026/08/uge-36-i-folketinget",body:["Folketinget skal behandle et forslag med princippet om, at ingen skal kunne ende med at betale mere i skat, end de tjener.","Den konkrete rækkevidde og de økonomiske konsekvenser skal belyses under Folketingets videre behandling."]},

  {c:"Erhverv",t:"Bavarian Nordic starter aktietilbagekøb for 250 millioner",d:"Første del af selskabets større program løber frem til slutningen af oktober.",time:"20:05",src:"Bavarian Nordic / Via Ritzau",url:"https://via.ritzau.dk/pressemeddelelse/15128146/bavarian-nordic-as?lang=en&publisherId=90446",body:["Bavarian Nordic har indledt første del af et aktietilbagekøbsprogram med en ramme på 250 millioner kroner.","Den samlede plan er på op til 750 millioner kroner. Første tranche kan omfatte op til 4,365 millioner aktier og løber efter planen til 30. oktober."]},
  {c:"Erhverv",t:"Storbanker planlægger fælles dollar-stablecoin",d:"Goldman Sachs, Bank of America og andre banker sigter mod lancering i 2027.",time:"18:38",src:"Reuters Technology",url:"https://www.reuters.com/technology/",body:["En gruppe store banker arbejder på en fælles stablecoin knyttet til den amerikanske dollar og med mulig lancering i 2027.","Initiativet viser, at traditionelle finanshuse i stigende grad vil konkurrere om digitale betalinger og tokeniserede aktiver."]},
  {c:"Erhverv",t:"Ny Venezuela-aftale giver USA stor rolle i olieproduktionen",d:"En omstridt aftale kan flytte kontrollen med olie og investeringer i landet.",time:"17:03",src:"Reuters",url:"https://www.reuters.com/",body:["En ny olieaftale med Venezuela giver amerikanske interesser en større rolle i produktionen og mulighed for at købe olie først.","Aftalen kan få betydning for både Venezuelas økonomi og det globale oliemarked, men de praktiske og politiske konsekvenser er endnu usikre."]},
  {c:"Erhverv",t:"G20 presser på for bedre balance i verdenshandlen",d:"Kinas import og store handelsoverskud er blandt de centrale emner.",time:"15:22",src:"Reuters",url:"https://www.reuters.com/",body:["G20-landene diskuterer, hvordan globale handelsubalancer kan mindskes, og hvordan flere store økonomier kan stimulere efterspørgslen.","Kinas store eksportoverskud og importniveau spiller en central rolle i debatten, der også handler om valutaer, investeringer og vækst."]},
  {c:"Erhverv",t:"Israels centralbank sænker renten for tredje møde i træk",d:"Renten sættes ned til 3,25 procent, efter at inflationen er forblevet lav.",time:"13:47",src:"Reuters",url:"https://www.reuters.com/world/middle-east/bank-israel-cuts-rates-third-straight-meeting-inflation-stays-low-2026-09-01/",body:["Israels centralbank har sænket styringsrenten med 0,25 procentpoint til 3,25 procent.","Det er tredje rentenedsættelse i træk. Beslutningen blev begrundet med lav inflation, men banken følger fortsat krigens og energiprisernes påvirkning af økonomien."]},

  {c:"Sport",t:"Ferrari hylder Schumacher med særlig Monza-bemaling",d:"Formel 1-holdet markerer et jubilæum med et historisk inspireret design.",time:"19:18",src:"Reuters Sport",url:"https://www.reuters.com/sports/",body:["Ferrari stiller til start på Monza med en særlig bemaling inspireret af Michael Schumachers æra hos holdet.","Markeringen forbinder årets italienske grandprix med en af de mest succesrige perioder i Ferraris Formel 1-historie."]},
  {c:"Sport",t:"Phillies slår Diamondbacks i tæt wildcard-kamp",d:"Philadelphia holder sig helt i toppen af kampen om en plads i slutspillet.",time:"17:54",src:"Reuters Sport",url:"https://www.reuters.com/sports/",body:["Philadelphia Phillies vandt en tæt kamp mod Arizona Diamondbacks og fastholdt sin position i kampen om National Leagues wildcardpladser.","Resultatet betyder, at holdene fortsat ligger tæt i en afgørende fase af baseballs grundspil."]},
  {c:"Sport",t:"NFL vil gøre kamp i Australien til en årlig begivenhed",d:"Ligaen undersøger en fast tilbagevenden som del af sin internationale ekspansion.",time:"16:21",src:"Reuters Sport",url:"https://www.reuters.com/sports/",body:["NFL ønsker at gøre en kamp i Australien til en tilbagevendende årlig begivenhed.","Planen er endnu et skridt i ligaens strategi om at nå fans uden for USA gennem grundspilskampe på nye markeder."]},
  {c:"Sport",t:"Naomi Osaka åbner US Open med sejr",d:"Den tidligere mester er sikkert videre efter sin første kamp i New York.",time:"14:42",src:"Reuters Sport",url:"https://www.reuters.com/sports/",body:["Naomi Osaka har vundet sin første kamp ved US Open og er videre til næste runde.","Den tidligere vinder er blandt turneringens mest fulgte profiler, og åbningssejren giver hende en rolig start på jagten efter endnu et stærkt resultat i New York."]},
  {c:"Sport",t:"VM i gadeløb samler løbere i København",d:"Halvmaraton, fem kilometer og en mile skal få både elite og motionister ud på ruten.",time:"12:36",src:"Danmarks Idrætsforbund / Via Ritzau",url:"https://via.ritzau.dk/pressemeddelelse/14782062/world-championships-in-copenhagen-aim-to-get-denmark-on-the-run?lang=da&publisherId=12522877",body:["København er vært for verdensmestersaberne i gadeløb den 19. og 20. september.","Programmet omfatter halvmaraton, fem kilometer og en mile og skal kombinere international eliteidræt med løb for et bredere publikum."]},

  {c:"Tech",t:"Anthropic indgår cloud-aftale til 35 milliarder dollar",d:"AI-selskabet vil sikre markant mere computerkraft gennem en stor aftale med Lambda.",time:"20:17",src:"Reuters Technology",url:"https://www.reuters.com/technology/",body:["Anthropic har indgået en cloud-aftale med Lambda med en oplyst værdi på 35 milliarder dollar.","Aftalen viser, hvor kapitalkrævende udviklingen af store AI-modeller er, og hvor hård konkurrencen om avancerede chips og datacenterkapacitet er blevet."]},
  {c:"Tech",t:"Waymo og Zoox udvider kampen om robotaxier",d:"De førerløse tjenester rykker ind i flere områder, mens konkurrencen skærpes.",time:"18:51",src:"Reuters Technology",url:"https://www.reuters.com/technology/",body:["Waymo og Zoox udvider deres robotaxitjenester til flere områder.","Udvidelserne bliver en vigtig test af teknologiens driftssikkerhed, myndighedernes krav og kundernes tillid til biler uden en menneskelig chauffør."]},
  {c:"Tech",t:"Oracle undersøges for licenspraksis i EU",d:"EU's konkurrencemyndigheder ser nærmere på vilkårene for virksomhedens softwarekunder.",time:"17:14",src:"Reuters Technology",url:"https://www.reuters.com/technology/",body:["Oracle er kommet under EU's konkurrencemæssige lup på grund af selskabets praksis for softwarelicenser.","Undersøgelsen skal afklare, om vilkårene begrænser kundernes valgmuligheder eller skaber urimelige barrierer på markedet."]},
  {c:"Tech",t:"TCL sagsøger Samsung i strid om betegnelsen Mini LED",d:"To elektronikgiganter tørner sammen om markedsføring og rettigheder til skærmteknologi.",time:"15:46",src:"Reuters Technology",url:"https://www.reuters.com/technology/",body:["TCL har anlagt sag mod Samsung i en konflikt om brugen af betegnelsen Mini LED.","Tvisten handler om, hvordan skærmteknologien må beskrives og markedsføres på et marked med hård konkurrence om premium-tv."]},
  {c:"Tech",t:"Cyberangreb hos Novocure berører over 1.400 patienter",d:"Personoplysninger blev eksponeret ved et sikkerhedsbrud hos medicoteknologiselskabet.",time:"13:29",src:"Reuters Technology",url:"https://www.reuters.com/technology/",body:["Et cyberangreb mod Novocure har eksponeret oplysninger om mere end 1.400 patienter.","Hændelsen understreger sundhedssektorens særlige risiko, fordi lækkede data kan være både følsomme og vanskelige at erstatte eller ændre."]},

  {c:"Gaming",t:"Crimson Moon udkommer i dag",d:"Det nye spil åbner september måneds tætpakkede udgivelseskalender.",time:"19:31",src:"GamesRadar",url:"https://www.gamesradar.com/video-game-release-dates/",body:["Crimson Moon udkommer 1. september og er dermed blandt månedens første nye spiltitler.","Lanceringen indleder en uge med flere udgivelser på tværs af PC og konsoller, hvor både store og mindre produktioner kæmper om spillernes opmærksomhed."]},
  {c:"Gaming",t:"Moonlighter 2 lander 2. september",d:"Efterfølgeren vender tilbage til blandingen af butiksliv, action og udforskning.",time:"17:59",src:"GamesRadar",url:"https://www.gamesradar.com/video-game-release-dates/",body:["Moonlighter 2 står til udgivelse 2. september.","Spillet bygger videre på seriens blanding af dungeon-eventyr og butiksdrift, hvor fund fra ekspeditionerne bliver en del af spillerens økonomi."]},
  {c:"Gaming",t:"Avatar Legends klar til lancering denne uge",d:"Det nye spil baseret på Avatar-universet står på kalenderen 3. september.",time:"16:27",src:"GamesRadar",url:"https://www.gamesradar.com/video-game-release-dates/",body:["Avatar Legends er planlagt til udgivelse 3. september.","Titlen bliver en del af en særligt travl udgivelsesdag og skal omsætte det kendte univers til en ny spiloplevelse."]},
  {c:"Gaming",t:"SpeedRunners 2 gør klar til start",d:"Efterfølgeren til det konkurrenceprægede platformspil udkommer 3. september.",time:"14:54",src:"GamesRadar",url:"https://www.gamesradar.com/video-game-release-dates/",body:["SpeedRunners 2 udkommer efter planen 3. september.","Serien er kendt for hurtige baner og lokal eller online konkurrence, hvor spillerne forsøger at løbe hinanden ud af skærmen."]},
  {c:"Gaming",t:"Onimusha: Way of the Sword udkommer 4. september",d:"Capcoms samurai-action er blandt ugens mest markante nye spil.",time:"12:43",src:"GamesRadar",url:"https://www.gamesradar.com/video-game-release-dates/",body:["Onimusha: Way of the Sword er sat til udgivelse 4. september.","Det nye kapitel genopliver Capcoms actionserie med sværdkampe, dæmoniske fjender og en historisk japansk ramme."]},

  {c:"Kultur",t:"Filmfestivalen i Venedig bliver mere politisk",d:"Globale konflikter fylder på årets festival, mens Hollywoods tilstedeværelse er mindre.",time:"20:44",src:"Reuters",url:"https://www.reuters.com/business/media-telecom/venice-film-festival-turns-politics-hollywood-retreats-2026-09-01/",body:["Årets filmfestival i Venedig er præget af politiske temaer og diskussioner om samtidens konflikter.","Samtidig er Hollywoods tilstedeværelse mindre end normalt, hvilket giver mere plads til europæiske og internationale produktioner på den røde løber."]},
  {c:"Kultur",t:"CD'en gør comeback i USA",d:"Salget af fysiske musikudgivelser hjælper den amerikanske musikbranche til ny vækst.",time:"18:19",src:"Reuters",url:"https://www.reuters.com/business/media-telecom/cds-make-comeback-boosting-us-recorded-music-revenue-2026-09-01/",body:["CD-salget vokser igen i USA og bidrager til stigende indtægter for den indspillede musikbranche.","Udviklingen følger vinylens genkomst og viser, at fysiske udgivelser fortsat har værdi for fans, selv om streaming dominerer den daglige lytning."]},
  {c:"Kultur",t:"20 millioner ekstra skal få flere til at bruge kulturpas",d:"En ny indsats skal løfte en ordning, som indtil nu har haft for få brugere.",time:"16:38",src:"Kulturministeriet",url:"https://kum.dk/",body:["Der afsættes 20 millioner kroner ekstra til kulturpasset, fordi for få unge indtil nu har taget ordningen i brug.","Pengene skal styrke kendskabet og gøre det nemmere at omsætte passet til konkrete oplevelser inden for kultur og foreningsliv."]},
  {c:"Kultur",t:"Fanø og højskoler indstillet til UNESCO-liste",d:"Danske levende kulturtraditioner kan få international anerkendelse.",time:"15:11",src:"Kulturministeriet",url:"https://kum.dk/",body:["Traditioner fra Fanø og de danske folkehøjskoler er blevet indstillet til UNESCOs liste over levende kulturarv.","En optagelse vil fremhæve praksisser og fællesskaber, der bliver ført videre mellem generationer, frem for fysiske monumenter og bygninger."]},
  {c:"Kultur",t:"Musik i Lejet fortsætter efter ekstraordinært møde",d:"Festivalen har fundet en vej videre efter en periode med usikkerhed.",time:"13:34",src:"Soundvenue",url:"https://soundvenue.com/",body:["Musik i Lejet fortsætter efter et ekstraordinært møde, skriver Soundvenue.","Afgørelsen skaber ny ro om festivalens fremtid, men arrangørerne skal fortsat omsætte beslutningen til en bæredygtig plan for de kommende år."]}
];
