const categoryImages={
  "Danmark":{url:"https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?auto=format&fit=crop&w=1400&q=78",credit:"Nick Karvounis / Unsplash",creditUrl:"https://unsplash.com/photos/26c3c8a854bc"},
  "Verden":{url:"https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1400&q=78",credit:"NASA / Unsplash",creditUrl:"https://unsplash.com/photos/43490279c0fa"},
  "Politik":{url:"https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1400&q=78",credit:"Joakim Honkasalo / Unsplash",creditUrl:"https://unsplash.com/photos/e1a2ed48a620"},
  "Erhverv":{url:"https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=1400&q=78",credit:"Jason Leung / Unsplash",creditUrl:"https://unsplash.com/photos/d334cdbbf45e"},
  "Sport":{url:"https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1400&q=78",credit:"Braden Collum / Unsplash",creditUrl:"https://unsplash.com/photos/ffe607ba8211"},
  "Tech":{url:"https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1400&q=78",credit:"Umberto / Unsplash",creditUrl:"https://unsplash.com/photos/4636190af475"},
  "Gaming":{url:"https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1400&q=78",credit:"Florian Olivo / Unsplash",creditUrl:"https://unsplash.com/photos/adc38448a05e"},
  "Kultur":{url:"https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=1400&q=78",credit:"Giammarco Boscaro / Unsplash",creditUrl:"https://unsplash.com/photos/b7833e8f5570"}
};

const stories=[
  {c:"Danmark",t:"Fem drenge sigtet efter sprængning ved skole i Kalundborg",d:"To 14-årige og tre 15-årige er sigtet efter en hændelse på Rynkevangskolens boldbane. Ingen kom til skade.",time:"17:30",src:"Midt- og Vestsjællands Politi",url:"https://politi.dk/midt-og-vestsjaellands-politi/nyhedsliste/fem-drenge-sigtet-efter-spraengning-ved-skole/2026/09/01",body:["Politiet modtog tirsdag formiddag en anmeldelse om en sprængning ved Rynkevangskolen i Kalundborg. På boldbanen fandt betjentene to flasker med kemikalier, hvoraf den ene var blevet bragt til sprængning.","Skolen blev evakueret, mens området blev undersøgt. Sprængstofhunde fandt ikke yderligere genstande, og EOD fjernede den sidste flaske. De fem drenge skal nu afhøres om deres roller og motivet."]},
  {c:"Danmark",t:"DSB overtager GoCollectives togtrafik fra i dag",d:"Overdragelsen skal sikre fortsat togdrift og bevare medarbejdernes tilknytning til trafikken.",time:"14:20",src:"Transportministeriet / Via Ritzau",url:"https://via.ritzau.dk/pressemeddelelse/15015116/dsb-overtager-gocollectives-togtrafik-fra-1-september-2026?lang=da&publisherId=5278762",body:["DSB overtager fra 1. september GoCollectives togtrafik. Aftalen skal holde togene kørende og betyder samtidig, at medarbejderne kan fortsætte i DSB-regi.","Transportministeren kalder overdragelsen et stort arbejde og oplyser, at både processen og den efterfølgende drift vil blive fulgt tæt."]},
  {c:"Danmark",t:"Traktordemonstration påvirker trafikken omkring Christiansborg",d:"Traktorer fra flere dele af Sjælland kører mod København i forbindelse med en anmeldt demonstration.",time:"10:05",src:"Københavns Politi",url:"https://politi.dk/koebenhavns-politi/nyhedsliste/vigtig-information-om-trafikken-tirsdag-morgen/2026/08/31",body:["Københavns Politi advarede om påvirket morgentrafik på Sjælland og i hovedstaden, da traktorer fra flere dele af landet kørte mod Christiansborg.","Demonstrationen var anmeldt til tirsdag formiddag. Trafikanter blev opfordret til at orientere sig om den aktuelle situation og beregne ekstra tid."]},
  {c:"Danmark",t:"60 millioner kroner afsat til ulvesikrede hegn",d:"En ny ansøgningsrunde giver husdyrholdere mulighed for at søge støtte frem til 1. oktober.",time:"10:43",src:"Ministeriet for Natur og Dyrevelfærd / Via Ritzau",url:"https://via.ritzau.dk/pressemeddelelse/15128937/60-millioner-afsat-til-ny-ansogningsrunde-til-ulvesikring-af-hegn?lang=da&publisherId=13562216",body:["Der er afsat yderligere 60 millioner kroner til ulvesikring. Pengene skal hjælpe husdyrholdere med at beskytte dyr i områder, hvor ulveangreb skaber udfordringer.","Den ordinære ordning er åben fra 1. september til 1. oktober. Der findes desuden en permanent akutordning for husdyrholdere, der allerede har oplevet et angreb."]},
  {c:"Danmark",t:"DMI og Klimadatastyrelsen samles i ny styrelse",d:"Sammenlægningen skal styrke arbejdet med ekstremvejr, kortlægning og klimatilpasning.",time:"12:10",src:"Klima-, Energi- og Forsyningsministeriet / Via Ritzau",url:"https://via.ritzau.dk/pressemeddelelse/15130330/dmi-og-klimadatastyrelsen-sammenlaegges-til-ny-styrelse?lang=da&publisherId=9426318",body:["Danmark skal ifølge ministeriet være bedre rustet til stormflod, skybrud og oversvømmelser. Derfor samles meteorologi, klimadata og dele af kortlægningsområdet i en ny organisation.","Sammenlægningen bliver også set i lyset af den sikkerhedspolitiske situation, hvor Forsvaret har brug for stærkere leverancer inden for terræn-, vejr- og isdata."]},

  {c:"Verden",t:"USA gennemfører nye angreb mod mål i Iran",d:"Angreb omkring Hormuzstrædet skærper igen spændingerne og presser energimarkederne.",time:"18:10",src:"Reuters",url:"https://www.reuters.com/world/",body:["USA har gennemført en ny bølge af angreb mod iranske mål omkring Hormuzstrædet. Udviklingen risikerer at genantænde en konflikt, der allerede har påvirket oliepriser og international handel.","Præsident Donald Trump kaldte angrebene berettigede og advarede Iran mod gengældelse. Situationen bliver fulgt tæt af både energimarkeder og regeringer i regionen."]},
  {c:"Verden",t:"Tyskland peger på Rusland efter droneangreb ved Leipzig",d:"Den tyske regering varsler modsvar efter konklusionen om et forsøg på angreb ved en central lufthavn.",time:"16:40",src:"Reuters",url:"https://www.reuters.com/world/europe/",body:["Tyskland siger, at Rusland stod bag et forsøg på et droneangreb ved Leipzig/Halle-lufthavnen. Regeringen har som reaktion annonceret en række diplomatiske tiltag.","Sagen føjer sig til Europas voksende bekymring over hybride angreb og sårbarheden omkring transportknudepunkter og kritisk infrastruktur."]},
  {c:"Verden",t:"Dødstallet efter oversvømmelser i Nepal passerer 1.000",d:"Redningsmandskab forsøger fortsat at nå afskårne områder efter katastrofale oversvømmelser.",time:"15:15",src:"Reuters",url:"https://www.reuters.com/",body:["Mere end 1.000 mennesker er ifølge myndighederne omkommet efter omfattende oversvømmelser i Nepal. Helikoptere og tungt materiel er sat ind for at nå isolerede landsbyer.","Tusinder er fortsat savnet, og katastrofen har igen rettet opmærksomheden mod farlige gletsjersøer og klimarisici i Himalaya."]},
  {c:"Verden",t:"Xi Jinping besøger Egypten midt i ny magtbalance i Mellemøsten",d:"Kinas præsident er landet i Kairo på sit første besøg i landet i et årti.",time:"13:55",src:"Reuters",url:"https://www.reuters.com/",body:["Xi Jinpings besøg finder sted, mens lande i Mellemøsten genovervejer deres sikkerheds- og handelspolitiske relationer efter krigen med Iran.","Kina ønsker at styrke sin rolle som økonomisk og diplomatisk partner i regionen, hvor energi, handel og stormagtsrivalisering fylder stadig mere."]},
  {c:"Verden",t:"Island siger nej til nye forhandlinger om EU-medlemskab",d:"Et tæt resultat endte med et nej til at genåbne optagelsesforhandlingerne.",time:"09:30",src:"Reuters",url:"https://www.reuters.com/video/watch/idRW897530082026RP1/",body:["Islands vælgere har i en tæt folkeafstemning afvist at genoptage forhandlinger om medlemskab af EU.","Fiskerettigheder og kontrollen over islandske farvande var blandt de centrale argumenter i debatten. Resultatet fastholder Island uden for unionen."]},

  {c:"Politik",t:"Statsministeren og EU-Kommissionens formand besøger Grønland",d:"Arktisk samarbejde og sikkerhed står centralt på dagsordenen for besøget.",time:"16:00",src:"Statsministeriet",url:"https://stm.dk/",body:["Statsministeriet oplyser, at statsministeren og EU-Kommissionens formand besøger Grønland. Turen kommer på et tidspunkt med øget europæisk fokus på Arktis.","Sikkerhed, råstoffer, klima og forholdet mellem Grønland, Danmark og EU ventes at være blandt de centrale emner."]},
  {c:"Politik",t:"Grønland, Færøerne og Danmark samles til møde",d:"Rigsfællesskabets tre lande mødes med udenrigs- og sikkerhedspolitik højt på dagsordenen.",time:"14:45",src:"Statsministeriet",url:"https://stm.dk/presse/pressemeddelelser/",body:["Ledelserne fra Grønland, Færøerne og Danmark samles til drøftelser. Mødet finder sted i en periode, hvor Arktis har fået større strategisk betydning.","Samarbejdet skal både håndtere fælles interesser og de tre landes forskellige politiske ønsker."]},
  {c:"Politik",t:"Finansloven sætter retningen for den kommende politiske sæson",d:"Regeringens forslag skal nu gennem Folketingets behandling og politiske forhandlinger.",time:"12:00",src:"Folketinget",url:"https://www.ft.dk/da/folkestyret/folketinget/finansloven",body:["Finanslovsforslaget er regeringens samlede bud på statens indtægter og udgifter. Det fremlægges senest ved udgangen af august og bliver et hovedtema, når Folketinget vender tilbage.","Forslaget skal fremsættes igen i oktober og forhandles med Folketingets partier, før en endelig finanslov kan vedtages."]},
  {c:"Politik",t:"Grøntsagsproducenter får pause fra ny kvælstofregulering",d:"Producenter undtages i 2027, mens der arbejdes på en mere målrettet løsning.",time:"11:35",src:"Ministeriet for Natur og Dyrevelfærd / Via Ritzau",url:"https://via.ritzau.dk/pressemeddelelse/15125154/grontsagsproducenter-undtages-fra-ny-kvaelstofregulering-i-2027?lang=da&publisherId=13562216",body:["Et politisk flertal har besluttet, at grøntsagsproducenter ikke bliver omfattet af den nye kvælstofregulering i 2027.","Aftalepartierne fastholder målet om bedre havmiljø, men vil bruge tiden på at finde en ordning, der tager højde for grøntsagsproduktionens særlige vilkår."]},
  {c:"Politik",t:"Minister foreslår at udfase byggeskadeforsikringen",d:"Et nyt lovforslag lægger op til at stoppe den obligatoriske ordning fra årsskiftet.",time:"09:50",src:"Social- og Boligministeriet / Via Ritzau",url:"https://via.ritzau.dk/pressemeddelelse/15129405/nyt-lovforslag-laegger-op-til-at-udfase-byggeskadeforsikringen?lang=da&publisherId=13566335",body:["Regeringen vil udfase byggeskadeforsikringen, som i dag skal tegnes ved opførelse af visse nye boliger.","Forslaget skal behandles politisk. Indtil reglerne eventuelt ændres, gælder de eksisterende krav fortsat."]},

  {c:"Erhverv",t:"Oliepriser og renter sender uro gennem verdens markeder",d:"Stigende energipriser styrker frygten for inflation og nye renteforhøjelser.",time:"17:20",src:"Reuters",url:"https://www.reuters.com/world/china/global-markets-global-markets-2026-09-01/",body:["Aktier faldt og statsrenter steg, da oliepriserne tog et nyt hop. Investorer frygter, at dyrere energi vil holde inflationen høj og tvinge centralbankerne til at stramme pengepolitikken.","Japans tiårige rente nåede 3 procent for første gang siden 1996, mens renterne også steg i Europa og USA."]},
  {c:"Erhverv",t:"Regeringen forventer det stærkeste danske opsving siden 1980'erne",d:"Eksport, forbrug og beskæftigelse trækker op — men væksten er koncentreret hos de største virksomheder.",time:"15:00",src:"Dansk Erhverv",url:"https://www.danskerhverv.dk/presse-og-nyheder/nyheder/2026/august/kommentar-regeringen-forventer-starkeste-okonomiske-opsving-siden-midten-af-80erne/",body:["Dansk økonomi står ifølge regeringens vurdering foran et usædvanligt kraftigt opsving. Eksporten og beskæftigelsen udvikler sig positivt, og husholdningernes forbrug er højt.","Dansk Erhverv advarer samtidig mod at overse, at en stor del af fremgangen drives af få meget store virksomheder."]},
  {c:"Erhverv",t:"Dell løfter forventningerne efter rekordstor AI-efterspørgsel",d:"Salget af servere til kunstig intelligens får teknologikoncernen til igen at hæve prognosen.",time:"13:30",src:"Reuters",url:"https://www.reuters.com/business/dell-again-lifts-forecasts-ai-demand-powers-record-results-2026-09-01/",body:["Dell har hævet sin prognose for både omsætning og indtjening efter stærk efterspørgsel efter AI-optimerede servere.","Selskabet forventer nu markant større serverindtægter, fordi cloududbydere investerer massivt i systemer med avancerede Nvidia-chips."]},
  {c:"Erhverv",t:"Sydkorea foreslår rekordbudget med massiv AI-satsning",d:"Et boom i halvlederindustrien skal finansiere investeringer i chips, forskning og fremtidig vækst.",time:"11:50",src:"Reuters",url:"https://www.reuters.com/world/asia-pacific/south-koreas-president-lee-says-interest-rate-rise-is-unavoidable-2026-09-01/",body:["Sydkoreas regering foreslår et rekordstort budget for 2027. En stor del af satsningen skal styrke kunstig intelligens og infrastrukturen omkring avancerede chips.","Stærke resultater hos Samsung og SK Hynix ventes at give staten ekstra skatteindtægter og dermed finansiere en del af væksten."]},
  {c:"Erhverv",t:"Shein får svær børsdebut i Hongkong",d:"Aktien faldt på første handelsdag amid regulatorisk usikkerhed og nervøse markeder.",time:"09:40",src:"Reuters",url:"https://www.reuters.com/commentary/reuters-open-interest/global-markets-view-usa-2026-09-01/",body:["Modeplatformen Sheins aktie faldt efter børsnoteringen i Hongkong. Debuten fandt sted på en dag præget af stigende renter og svagere risikovillighed.","Selskabet er samtidig under pres fra regulatoriske spørgsmål på flere markeder."]},

  {c:"Sport",t:"Alcaraz stærkt tilbage — Sabalenka åbner jagten på tredje titel",d:"To af US Opens største profiler kom sikkert videre på turneringens anden dag.",time:"18:25",src:"Reuters Sport",url:"https://www.reuters.com/sports/",body:["Carlos Alcaraz vandt sin første singlekamp i 139 dage, mens Aryna Sabalenka åbnede sit forsøg på at vinde US Open for tredje år i træk med en sejr.","Turneringen i New York samler igen tennisens største navne, og begge favoritter fik en lovende start."]},
  {c:"Sport",t:"Rybakina, Fritz og Keys videre på regnramt dag i New York",d:"Regn skabte forsinkelser, men flere topnavne spillede sig sikkert til næste runde.",time:"16:55",src:"Reuters",url:"https://www.reuters.com/sports/tennis/us-open-day-three-2026-09-01/",body:["Elena Rybakina, Taylor Fritz og Madison Keys vandt deres kampe på US Opens tredje dag. Flere udendørskampe blev forsinket af vejret.","Flavio Cobolli leverede dagens store comeback ved at vende et truende nederlag efter at have tabt de første to sæt."]},
  {c:"Sport",t:"Manchester City vil hente Fernandez for britisk rekordbeløb",d:"Ifølge rapporter er klubben enig med Chelsea om en opsigtsvækkende handel.",time:"14:10",src:"Reuters Sport",url:"https://www.reuters.com/sports/",body:["Manchester City har ifølge flere rapporter indgået en aftale om at købe Fernandez fra Chelsea for et beløb, der vil sætte britisk transferrekord.","Handlen understreger endnu en sommer med meget store beløb i toppen af Premier League."]},
  {c:"Sport",t:"Barcelona henter Gabriel Jesus fra Arsenal",d:"Den brasilianske angriber skifter til den spanske storklub.",time:"12:35",src:"Reuters Sport",url:"https://www.reuters.com/sports/",body:["Barcelona har skrevet kontrakt med den brasilianske angriber Gabriel Jesus fra Arsenal.","Skiftet giver Barcelona en erfaren offensiv profil, mens Arsenal skal finde en ny balance i angrebet."]},
  {c:"Sport",t:"Lionel Messi stopper på Argentinas landshold",d:"En af fodboldhistoriens største spillere afslutter sin internationale karriere.",time:"10:20",src:"Reuters Sport",url:"https://www.reuters.com/sports/",body:["Lionel Messi har meddelt, at hans tid på Argentinas landshold er forbi. Dermed slutter et historisk kapitel for både spilleren og nationen.","Messi forlader landsholdet som verdensmester og som en af de mest indflydelsesrige spillere i international fodbold."]},

  {c:"Tech",t:"John Ternus overtager som Apples nye topchef",d:"Tim Cook fortsætter som bestyrelsesformand efter 15 år i spidsen for teknologigiganten.",time:"17:45",src:"Associated Press",url:"https://apnews.com/article/2fac80118828b4ada9d160d012c7be32",body:["John Ternus er officielt tiltrådt som administrerende direktør for Apple. Han kommer fra en lang karriere i selskabets hardwareorganisation.","Han overtager på et tidspunkt, hvor Apple skal accelerere sin AI-strategi og samtidig forsvare iPhonens centrale rolle. Tim Cook bliver i virksomheden som bestyrelsesformand."]},
  {c:"Tech",t:"EU spørger medier om Googles nye AI-fravalg",d:"Forlag skal vurdere, om de reelt kan sige nej til AI-resuméer uden at miste synlighed i søgninger.",time:"16:10",src:"Reuters",url:"https://www.reuters.com/legal/litigation/eu-antitrust-regulators-quiz-publishers-googles-ai-search-opt-out-2026-09-01/",body:["EU's konkurrencemyndigheder undersøger Googles forslag til et fravalg af AI-funktioner i søgemaskinen.","Medier har kritiseret AI-resuméer for at bruge deres indhold og samtidig mindske trafikken til originalartiklerne. EU vil vurdere, om Googles løsning er tilstrækkelig."]},
  {c:"Tech",t:"USA presser på for færre globale regler om kunstig intelligens",d:"Ved et G20-møde argumenterer USA for innovation og investeringer frem for nye kontrolorganer.",time:"14:50",src:"Reuters",url:"https://www.reuters.com/legal/litigation/us-urge-hands-off-ai-regulation-g-20-official-says-2026-09-01/",body:["USA opfordrer G20-landene til at holde igen med nye regler for AI. Målet er at undgå, at regulering bremser forskning og kommerciel udvikling.","Andre lande fremhæver samtidig behovet for sikkerhedsforanstaltninger, ansvar og beskyttelse mod misbrug."]},
  {c:"Tech",t:"AI-servere sender Dell mod nyt rekordår",d:"Virksomheden forventer nu en markant større forretning inden for datacentre.",time:"12:25",src:"Reuters",url:"https://www.reuters.com/business/dell-again-lifts-forecasts-ai-demand-powers-record-results-2026-09-01/",body:["Efterspørgslen efter servere bygget til AI-træning og drift vokser hurtigere end ventet. Dell har derfor for anden gang i år hævet sine forventninger.","Udviklingen viser, hvor store investeringer teknologiselskaber og cloududbydere foretager i fysisk AI-infrastruktur."]},
  {c:"Tech",t:"Energiselskaber møder en ny bølge af AI-forstærkede cyberangreb",d:"Mere digitaliserede elnet giver angribere flere indgange til kritisk infrastruktur.",time:"09:15",src:"Reuters",url:"https://www.reuters.com/business/energy/energy-firms-face-ai-enhanced-cyber-attacks-connectivity-push--reeii-2026-09-01/",body:["Hackere bruger i stigende grad kunstig intelligens til at finde svagheder, automatisere angreb og målrette medarbejdere i energisektoren.","Små forsyningsselskaber med ældre systemer vurderes at være særligt udsatte. Eksperter efterlyser bedre overvågning, opdateringer og fælles sikkerhedsstandarder."]},

  {c:"Gaming",t:"Tusindvis af Xbox-ansatte ramt af omfattende fyringsrunde",d:"Medarbejdere beskriver sorg og usikkerhed efter en stor omstrukturering i Microsofts spildivision.",time:"18:00",src:"The Guardian",url:"https://www.theguardian.com/games/2026/sep/01/xbox-layoffs-microsoft",body:["Microsofts Xbox-division har gennemført en omfattende omstrukturering, der ifølge The Guardian har kostet tusindvis af job på tværs af studier.","Ansatte fra blandt andet Bethesda- og ZeniMax-miljøet fortæller om brat kommunikation og usikkerhed om både projekter og fratrædelsesvilkår."]},
  {c:"Gaming",t:"September bliver tæt pakket med store spiludgivelser",d:"Nye titler rammer PC, PlayStation, Xbox og Switch næsten hver uge.",time:"15:40",src:"GamesRadar",url:"https://www.gamesradar.com/video-game-release-dates/",body:["September byder på en usædvanligt tæt udgivelseskalender. Blandt titlerne er The Blood of Dawnwalker, Onimusha: Way of the Sword og EA Sports FC 27.","Kalenderen spænder fra store actionspil til sport og indieudgivelser på tværs af de største platforme."]},
  {c:"Gaming",t:"Xbox Game Pass får ny september-bølge",d:"Black Ops: Cold War og SpeedRunners 2 er blandt spillene på vej til tjenesten.",time:"13:15",src:"DayOne",url:"https://playday.one/",body:["Microsoft har præsenteret første bølge af septembertitler til Game Pass. Udvalget rummer både større etablerede navne og nye udgivelser.","Tilføjelserne kommer midt i en periode med store organisatoriske ændringer hos Xbox."]},
  {c:"Gaming",t:"GTA 6-visning topper Netflix-lister med millioner af seere",d:"En længere præsentation af det kommende spil har trukket et enormt publikum.",time:"11:30",src:"DayOne",url:"https://playday.one/",body:["En udvidet præsentation af GTA 6 har ifølge DayOne passeret 31 millioner visninger og nået toppen af Netflix' lister.","Interessen understreger de enorme forventninger til Rockstars næste Grand Theft Auto."]},
  {c:"Gaming",t:"Ny Black Flag-opdatering lader spillere klappe hunden",d:"En lille detalje i den nye patch vækker stor begejstring blandt Assassin's Creed-fans.",time:"09:20",src:"DayOne",url:"https://playday.one/",body:["En ny opdatering til Assassin's Creed Black Flag Resynced tilføjer blandt andet muligheden for at interagere med og klappe en hund.","Det er en lille funktion, men den type detaljer bliver ofte hurtigt populære i gamingfællesskaber."]},

  {c:"Kultur",t:"Tre danske film udtaget til festivalen i Toronto",d:"To af filmene får verdenspremiere ved en af efterårets vigtigste internationale filmfestivaler.",time:"17:05",src:"Det Danske Filminstitut",url:"https://www.dfi.dk/nyheder/dansk-film-paa-toronto-film-festival",body:["Tre danske film er på programmet ved Toronto International Film Festival fra 10. til 20. september.","To af produktionerne får verdenspremiere. Udtagelsen giver dansk film synlighed over for både et internationalt publikum og filmbranchen."]},
  {c:"Kultur",t:"Unge får gratis adgang til mere end 200 danske museer",d:"18-27-årige kan i en uge besøge en lang række museer uden at betale entré.",time:"15:25",src:"The Local Denmark",url:"https://www.thelocal.dk/tag/culture",body:["Fra 7. til 13. september tilbyder mere end 200 museer gratis adgang for unge mellem 18 og 27 år.","Initiativet skal åbne kulturlivet for flere unge og gøre det lettere at opdage både kunst, historie og lokale samlinger."]},
  {c:"Kultur",t:"September byder på flere nye danske biograffilm",d:"Filminstituttets kalender tæller blandt andet No Rest for the Wicked og Dobbeltfejl.",time:"13:10",src:"Det Danske Filminstitut",url:"https://www.dfi.dk/nyheder/kommendefilm",body:["Flere danske film får premiere i september. DFI's oversigt fremhæver blandt andet No Rest for the Wicked den 3. september samt Brohr og Dobbeltfejl den 24. september.","Efterårets premiereprogram viser en blanding af genrer og både etablerede og nyere filmskabere."]},
  {c:"Kultur",t:"Netflix åbner september med både nye film og klassikere",d:"En ny biografisk film og en dokumentar får selskab af blandt andet Alien og Phantom Thread.",time:"11:05",src:"Entertainment Weekly",url:"https://ew.com/movies-coming-to-netflix-september-2026-12074156",body:["Netflix' septemberprogram rummer den biografiske Unabomber med Jacob Tremblay og dokumentaren Untold Raygun: Breaking Badly.","Samtidig vender en række kendte titler tilbage, herunder Alien, Phantom Thread og The Texas Chain Saw Massacre."]},
  {c:"Kultur",t:"Dansk film står stærkt på septembers internationale festivaler",d:"Nye danske produktioner rejser ud til et tæt efterårsprogram af filmfestivaler.",time:"09:35",src:"Det Danske Filminstitut",url:"https://www.dfi.dk/nyheder",body:["September er en vigtig måned for dansk film internationalt. Flere produktioner vises på store festivaler, hvor de møder distributører, presse og publikum.","Festivaldeltagelse kan få stor betydning for filmenes videre liv og mulighed for international distribution."]}
];

stories.forEach((s,i)=>{s.id=i;s.image=categoryImages[s.c]});
const cats=["Alle","Danmark","Verden","Politik","Erhverv","Sport","Tech","Gaming","Kultur"];
let selected="Alle",query="";
const $=s=>document.querySelector(s);
const nav=$("#nav"),grid=$("#grid");

function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function image(s,article=false){return `<img src="${s.image.url}" alt="" loading="${article?"eager":"lazy"}"><span class="credit">Foto: <a href="${s.image.creditUrl}" target="_blank" rel="noopener">${esc(s.image.credit)}</a></span>`}
function storyUrl(id){return `article.html?id=${id}`}
function goStory(id){window.location.href=storyUrl(id)}
function card(s){return `<article class="card" data-id="${s.id}" tabindex="0" role="link" aria-label="Læs: ${esc(s.t)}"><div class="thumb">${image(s)}<span class="tag">${s.c}</span></div><div class="body"><div class="meta"><span>${s.time}</span><span>3 min.</span></div><h3>${esc(s.t)}</h3><p>${esc(s.d)}</p><span class="source">Kilde: ${esc(s.src)} ↗</span></div></article>`}
function render(){
  const list=stories.filter(s=>(selected==="Alle"||s.c===selected)&&(!query||(s.t+" "+s.d+" "+s.c).toLowerCase().includes(query)));
  grid.innerHTML=list.map(card).join("");$("#empty").classList.toggle("show",!list.length);$("#count").textContent=`${list.length} historier`;$("#sectionTitle").textContent=selected==="Alle"?(query?"Søgeresultater":"Alle nyheder"):selected;
  document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.cat===selected));
}
function setup(){
  nav.innerHTML=cats.map(c=>`<button data-cat="${c}">${c}</button>`).join("");
  const featured=[stories[5],stories[0],stories[15],stories[20],stories[25],stories[30],stories[35]];
  let slide=0,timer;
  function showSlide(next,animate=true){
    slide=(next+featured.length)%featured.length;
    const lead=featured[slide],el=$("#lead");
    if(animate)el.classList.add("changing");
    setTimeout(()=>{
      el.innerHTML=`${image(lead,true)}<span class="slidecount">${String(slide+1).padStart(2,"0")} / ${String(featured.length).padStart(2,"0")}</span><div class="leadcopy"><span class="tag">${lead.c}</span><h1>${esc(lead.t)}</h1><p>${esc(lead.d)}</p></div><div class="slider-dots" aria-label="Vælg fremhævet nyhed">${featured.map((_,i)=>`<button class="slider-dot ${i===slide?"active":""}" data-slide="${i}" aria-label="Nyhed ${i+1}"></button>`).join("")}</div><div class="slider-nav"><button class="slider-arrow" data-dir="-1" aria-label="Forrige nyhed">‹</button><button class="slider-arrow" data-dir="1" aria-label="Næste nyhed">›</button></div>`;
      el.dataset.id=lead.id;el.classList.remove("changing");
    },animate?180:0);
  }
  function auto(){clearInterval(timer);if(!matchMedia("(prefers-reduced-motion: reduce)").matches)timer=setInterval(()=>showSlide(slide+1),6000)}
  showSlide(0,false);auto();
  $("#lead").onclick=e=>{const dot=e.target.closest("[data-slide]"),arrow=e.target.closest("[data-dir]");if(dot){e.stopPropagation();showSlide(+dot.dataset.slide);auto()}else if(arrow){e.stopPropagation();showSlide(slide+(+arrow.dataset.dir));auto()}else if(!e.target.closest(".credit"))goStory(+e.currentTarget.dataset.id)};
  $("#lead").onkeydown=e=>{if((e.key==="Enter"||e.key===" ")&&!e.target.matches("button,a")){e.preventDefault();goStory(+e.currentTarget.dataset.id)}};
  $("#lead").onmouseenter=()=>clearInterval(timer);$("#lead").onmouseleave=auto;
  $("#latest").innerHTML=stories.slice(0,5).map(s=>`<a href="${storyUrl(s.id)}"><time>${s.time}</time><h3>${esc(s.t)}</h3></a>`).join("");
  $("#ticker").textContent=stories[0].t;
  nav.onclick=e=>{if(e.target.dataset.cat){selected=e.target.dataset.cat;query="";$("#searchInput").value="";render();window.scrollTo({top:430,behavior:"smooth"})}};
  grid.onclick=e=>{const c=e.target.closest(".card");if(c)goStory(+c.dataset.id)};
  grid.onkeydown=e=>{const c=e.target.closest(".card");if(c&&(e.key==="Enter"||e.key===" ")){e.preventDefault();goStory(+c.dataset.id)}};
  $("#searchBtn").onclick=()=>{$("#search").classList.add("open");setTimeout(()=>$("#searchInput").focus(),30)};
  $("#menuBtn").onclick=()=>document.querySelector(".nav").scrollIntoView({behavior:"smooth"});
  $("#closeSearch").onclick=()=>$("#search").classList.remove("open");
  $("#searchInput").oninput=e=>{query=e.target.value.trim().toLowerCase();selected="Alle";render()};
  $("#searchInput").onkeydown=e=>{if(e.key==="Enter")$("#search").classList.remove("open")};
  const requested=new URLSearchParams(location.search).get("category");if(cats.includes(requested))selected=requested;
  render();
}
window.FokusData={stories,cats,esc,image,storyUrl};
if(document.querySelector("#nav"))setup();
